export enum ItemType {
    INGREDIENT = "INGREDIENT",
    BEVERAGE = "BEVERAGE",
    SAUCE = "SAUCE",
    CONSUMABLE = "CONSUMABLE",
    RECIPE = "RECIPE",
    PACKAGE = "PACKAGE",
    SIMPLE_PACKAGE = "SIMPLE_PACKAGE"
}