package sms.enums;

public enum PermissionType {
	PRODUCT_CREATE, PRODUCT_UPDATE, PRODUCT_DELETE, PRODUCT_FULL,

	CATEGORY_CREATE, CATEGORY_UPDATE, CATEGORY_DELETE, CATEGORY_FULL,

	CATALOGUE_CREATE, CATALOGUE_UPDATE, CATALOGUE_DELETE, CATALOGUE_FULL,

	OPERATOR_FULL,

	ADMINISTRATOR_FULL
}
